### ISSUE TITLE
Update envoy to the latest stable version

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#2164]
**What would you like to be added**:

**Why is this needed**:

**Comment by nakabonne** [comment]
From https://github.com/pipe-cd/pipe/pull/2162

Our current default version of Envoy is 1.10 which supports only v2 API. We'd better bump Envoy to after v1.13 (current latest is v1.19) as soon as possible because [V2 API is no longer supported](https://www.envoyproxy.io/docs/envoy/latest/api/api_supported_versions).
